services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=changemeinprod'
      - 'POSTGRES_USER=andruf'
    ports:
      - '5432:5432'